[SERVICE]
    Flush        2
    Daemon       Off
    Log_Level    info
    #storage.path /home/devdaniel/fluent-bit-storage/
    #storage.sync normal



[INPUT]
    name                tail    
    path                ./data/dataset-*.txt
    exit_on_eof         true
    read_from_head      true        
    DB                  ./log/flb_dataet.db    
    parser              datasetTxt   
    Tag                 dataset     
    Path_Key            file_path
    Buffer_Chunk_Size   64k
    Buffer_Max_Size     64k
    Mem_Buf_Limit       64k
    #storage.type        filesystem    
    #Skip_Empty_Lines    On    
    # Para ignorar la primera línea (header)
    #Exec                sed -i '1d' /home/devdaniel/DataEngineer/PL_Jikko_FluentBitKafkaPostgres/data/dataset-*.txt
    #Mem_Buf_Limit       100MB

#[FILTER]
#    Name                modify
#    Match               dataset
#    Condition           Key_value_equals estrato ""
#    Set                 estrato -1

[FILTER]
    Name                lua
    Match               dataset
    Script              batch_control.lua
    Call                process



#[OUTPUT]
#    name        stdout
#    match       *       
#    Format      json_lines
[OUTPUT]
    Name  stdout
    Match *

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     127.0.0.1:29092
    Topics      pipeline
