[PARSER]
    Name        datasetTxt
    Format      regex
    Regex       ^(?<id>[^,]+),(?<anio>\d{4}),(?<destino>[^,]*),(?<estrato>[^,]*|-1 ),(?<consumo>[0-9.]+)$
    Types       anio:integer,consumo:float,estrato:string
    #Time_Key    anio
    #Time_Format %Y